#!/usr/bin/env python2
# coding: utf-8
# comodit | A command line client for ComodIT

import sys

from comodit_client import dispatch

def main(argv):
    dispatch.run(argv)

if __name__ == "__main__":
    main(sys.argv[1:])
